<?php
$educationDegrees = [
    ['name' => 'SSC', 'icon' => 'mdi-school'],
    ['name' => 'HSC', 'icon' => 'mdi-school'],
    ['name' => 'CBSE', 'icon' => 'mdi-book-open'],
    ['name' => 'ICSE', 'icon' => 'mdi-book-open'],
    ['name' => 'Diploma in Engineering', 'icon' => 'mdi-engine'],
    ['name' => 'Diploma in Pharmacy', 'icon' => 'mdi-pill'],
    ['name' => 'Diploma in Education (D.Ed)', 'icon' => 'mdi-teach'],
    ['name' => 'Diploma in Nursing', 'icon' => 'mdi-hospital'],
    ['name' => 'Diploma in Hotel Management', 'icon' => 'mdi-hotel'],
    ['name' => 'Diploma in Fine Arts', 'icon' => 'mdi-palette'],
    ['name' => 'Diploma in Fashion Designing', 'icon' => 'mdi-tshirt-crew'],
    ['name' => 'BA', 'icon' => 'mdi-book'],
    ['name' => 'BSc', 'icon' => 'mdi-book'],
    ['name' => 'BCom', 'icon' => 'mdi-book'],
    ['name' => 'BTech', 'icon' => 'mdi-laptop'],
    ['name' => 'BE', 'icon' => 'mdi-laptop'],
    ['name' => 'MBBS', 'icon' => 'mdi-stethoscope'],
    ['name' => 'BDS', 'icon' => 'mdi-tooth'],
    ['name' => 'BPharm', 'icon' => 'mdi-pill'],
    ['name' => 'BBA', 'icon' => 'mdi-briefcase'],
    ['name' => 'BCA', 'icon' => 'mdi-code-braces'],
    ['name' => 'B.Ed', 'icon' => 'mdi-teach'],
    ['name' => 'LLB', 'icon' => 'mdi-gavel'],
    ['name' => 'BArch', 'icon' => 'mdi-home-modern'],
    ['name' => 'BFA', 'icon' => 'mdi-palette'],
    ['name' => 'MA', 'icon' => 'mdi-book'],
    ['name' => 'MSc', 'icon' => 'mdi-book'],
    ['name' => 'MCom', 'icon' => 'mdi-book'],
    ['name' => 'MTech', 'icon' => 'mdi-laptop'],
    ['name' => 'ME', 'icon' => 'mdi-laptop'],
    ['name' => 'MBA', 'icon' => 'mdi-briefcase'],
    ['name' => 'MCA', 'icon' => 'mdi-code-braces'],
    ['name' => 'MPharm', 'icon' => 'mdi-pill'],
    ['name' => 'LLM', 'icon' => 'mdi-gavel'],
    ['name' => 'M.Ed', 'icon' => 'mdi-teach'],
    ['name' => 'MSW', 'icon' => 'mdi-account-group'],
    ['name' => 'MFA', 'icon' => 'mdi-palette'],
    ['name' => 'PhD', 'icon' => 'mdi-graduation-cap'],
    ['name' => 'MD', 'icon' => 'mdi-stethoscope'],
    ['name' => 'MS', 'icon' => 'mdi-stethoscope'],
    ['name' => 'DDS', 'icon' => 'mdi-tooth'],
    ['name' => 'DBA', 'icon' => 'mdi-briefcase'],
    ['name' => 'CA', 'icon' => 'mdi-account-cash'],
    ['name' => 'CMA', 'icon' => 'mdi-account-cash'],
    ['name' => 'CS', 'icon' => 'mdi-file-document'],
    ['name' => 'CFP', 'icon' => 'mdi-account-cash'],
    ['name' => 'CISA', 'icon' => 'mdi-security'],
    ['name' => 'PMP', 'icon' => 'mdi-clipboard-check'],
    ['name' => 'CPA', 'icon' => 'mdi-account-cash']
];

?>